### ISSUE TITLE
Request: Ability to reset low food level from Home Assistant

### ISSUE THREAD

**Issue by BSkando** [n6ham/esphome-configs#1]
Greetings!  Thank you for this awesome config!  It has been working quite well.

I do wish there was a way to reset the low food level from home assistant rather than from the phyiscal button only.  I would put in a PR for this, but my programming skills are not quite up to that point yet.

Thank you!

**Comment by n6ham** [comment]
Hello! 

Could you please clarify what would be the desired behavior of the new HA button?

a) Do you want it re-set the last dispensed food count to trick the feeder into thinking that it's not low on food?
b) Or just silence the consequent reminders (notification + sound) that happen hourly between 7-22, but keep the `feeder_state` as "Food level is low" until food is dispensed and the updated food count goes above the threshold?

UPD: Thank you, I'm happy to hear this config is useful for someone else!

**Comment by BSkando** [comment]
b) should be fine.  My daughter was at home alone when the food ran out the other day and it freaked her out.

Maybe I had a misunderstanding how the config works.  Does the low level persist ONLY until the feeder successfully dispenses?  Or does the physical button on the unit need to be pressed to clear the Low Level state?

OFF TOPIC:
Yes this config has been fantastic!  I may end up altering it to feed at specific times inside the actual ESPHome config, in case something happens with my Home Assistant VM while I'm on vacation.  That way the feeding is independent of the HA config.  

I know you mentioned not wanting to build that into the config due to potential difficulty.  What you might be able to do instead is add the ability to allow scheduling inside the ESPHome config, but comment out the section.  That way people like me with SOME ESPHome coding knowledge can still make that work and delete the Home Assistant scheduling function.  I can submit a separate issue if necessary.  I can also just submit a PR if I get it figured out

**Comment by n6ham** [comment]
> b) should be fine. My daughter was at home alone when the food ran out the other day and it freaked her out.

Oh, okay. Was it the sound of a beeper that freaked her out? 
A quicker alternative solution would be to just mute sounds by turning on the `mute_sounds` switch in HA dashboard. Or do you want to still get notified by the beeper at least once?

> Does the low level persist ONLY until the feeder successfully dispenses?

Yes, it persists until the feeder dispensed the food and the food count (a sensor state) goes above the threshold. I.e. the feeder thinks that the food level is low as long as this condition is true:
```
id(last_food_scoops_count) > 0 && id(last_food_sensor_count) / id(last_food_scoops_count) < id(low_food_threshold).state
```

> Or does the physical button on the unit need to be pressed to clear the Low Level state?

It won't reset anything per se, but trigger the food dispensing. Whether "low food level" will be reset depends on the quantity of the dispensed food, not on the button press itself. I.e. if there little/no food in a hopper, and you pressed a physical button on the side - the feeder will just detect low food level again (and beep and send notification).

> I may end up altering it to feed at specific times inside the actual ESPHome config, in case something happens with my Home Assistant VM while I'm on vacation.

Hm... actually the schedule should be HA-independent as is. I had exactly the same desire to make my feeders as fail-safe as possible.

The idea was that you only need HA to *change* the feeding schedule by setting a number of scoops to be dispensed by the feeder at a certain hour. 

All this information is stored in the feeder itself in the template numbers `schedule_cups_0000`, `schedule_cups_0100`, ..., `schedule_cups_2300`. The feeder should dispense the food at the configured hours even when HA is down.

For all fairness though, I have never tested it this way to ensure that it feeds even when HA is down and even after the power outage/restart (but it should since I set `restore_value: true`).

**Comment by BSkando** [comment]
I like getting the beeper for feeding.  However, I now realize I can just make an automation for the mute sounds within HA, so no need to change anything.

That makes sense now, I won't tinker with it then!  Looks like this can be closed.

Thanks for the detailed responses.  Helped explain a lot of this stuff.
